# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/GT-I9000/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries 

PRODUCT_COPY_FILES := \
    vendor/samsung/GT-I9000/prebuilt/lib/libgps.so:obj/lib/libgps.so \
    vendor/samsung/GT-I9000/system/lib/libclientgps.so:obj/lib/libclientgps.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsecgps.so:obj/lib/libsecgps.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsecril-client.so:obj/lib/libsecril-client.so

#
# WiFi & Bluetooth
#
PRODUCT_COPY_FILES +=     vendor/samsung/GT-I9000/prebuilt/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/bcm4329_aps.bin:system/etc/wifi/bcm4329_aps.bin \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/bcm4329_mfg.bin:system/etc/wifi/bcm4329_mfg.bin \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/bcm4329_sta.bin:system/etc/wifi/bcm4329_sta.bin \
    vendor/samsung/GT-I9000/prebuilt/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/wifi.conf:system/etc/wifi/wifi.conf \
    vendor/samsung/GT-I9000/prebuilt/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/GT-I9000/prebuilt/lib/libwlservice.so:system/lib/libwlservice.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libwifitest.so:system/lib/libwifitest.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/samsung/GT-I9000/prebuilt/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/samsung/GT-I9000/prebuilt/bin/btld:system/bin/btld \
    vendor/samsung/GT-I9000/prebuilt/bin/BCM4329B1_002.002.023.0417.0430.hcd:system/bin/BCM4329B1_002.002.023.0417.0430.hcd \
    vendor/samsung/GT-I9000/prebuilt/bin/wlservice:system/bin/wlservice

#
# Display (3D)
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/egl/libEGL_POWERVR_SGX540_120.so:system/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/samsung/GT-I9000/prebuilt/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/GT-I9000/prebuilt/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/samsung/GT-I9000/prebuilt/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libIMGegl.so:system/lib/libIMGegl.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libpvr2d.so:system/lib/libpvr2d.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsrv_init.so:system/lib/libsrv_init.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsrv_um.so:system/lib/libsrv_um.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/GT-I9000/prebuilt/bin/pvrsrvinit:system/bin/pvrsrvinit

#
# Sensors, Lights etc
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/hw/copybit.s5pc110.so:system/lib/hw/copybit.s5pc110.so \
    vendor/samsung/GT-I9000/prebuilt/lib/hw/lights.s5pc110.so:system/lib/hw/lights.s5pc110.so \
    vendor/samsung/GT-I9000/prebuilt/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/GT-I9000/prebuilt/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/samsung/GT-I9000/prebuilt/lib/hw/gralloc.s5pc110.so:system/lib/hw/gralloc.s5pc110.so \
    vendor/samsung/GT-I9000/prebuilt/bin/sensorcalibutil_yamaha:system/bin/sensorcalibutil_yamaha \
    vendor/samsung/GT-I9000/prebuilt/bin/sensorserver_yamaha:system/bin/sensorserver_yamaha \
    vendor/samsung/GT-I9000/prebuilt/bin/sensorstatutil_yamaha:system/bin/sensorstatutil_yamaha \
    vendor/samsung/GT-I9000/prebuilt/lib/libms3c_yamaha.so:system/lib/libms3c_yamaha.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsensor_yamaha.so:system/lib/libsensor_yamaha.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsensor_yamaha_test.so:system/lib/libsensor_yamaha_test.so

#
# Camera
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libcamerafirmwarejni.so:system/lib/libcamerafirmwarejni.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libcamera.so:system/lib/libcamera.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libseccameraadaptor.so:system/lib/libseccameraadaptor.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libseccamera.so:system/lib/libseccamera.so

#
# RIL
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/libril.so:system/lib/libril.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/GT-I9000/prebuilt/bin/drexe:system/bin/drexe \
    vendor/samsung/GT-I9000/prebuilt/bin/rild:system/bin/rild \
    vendor/samsung/GT-I9000/prebuilt/bin/rilclient-test:system/bin/rilclient-test

#
# GPS
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/libgps.so:system/lib/libgps.so \
    vendor/samsung/GT-I9000/system/lib/libclientgps.so:system/lib/libclientgps.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsecgps.so:system/lib/libsecgps.so
    
#
# OMX
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/libs263domxoc.so:system/lib/libs263domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libs263eomxoc.so:system/lib/libs263eomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libs264domxoc.so:system/lib/libs264domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libs264eomxoc.so:system/lib/libs264eomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsaacdomxoc.so:system/lib/libsaacdomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsaaceomxoc.so:system/lib/libsaaceomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsac3domxoc.so:system/lib/libsac3domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsamrdomxoc.so:system/lib/libsamrdomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsamreomxoc.so:system/lib/libsamreomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsdiv3domxoc.so:system/lib/libsdiv3domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsflacdomxoc.so:system/lib/libsflacdomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsmp3domxoc.so:system/lib/libsmp3domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsmp4fmocn.so:system/lib/libsmp4fmocn.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsmp4vdomxoc.so:system/lib/libsmp4vdomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsmp4veomxoc.so:system/lib/libsmp4veomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libsvc1domxoc.so:system/lib/libsvc1domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libswmadomxoc.so:system/lib/libswmadomxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libswmv7domxoc.so:system/lib/libswmv7domxoc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libswmv8domxoc.so:system/lib/libswmv8domxoc.so

#
# PPP
#
PRODUCT_COPY_FILES +=     vendor/samsung/GT-I9000/prebuilt/bin/pppd:system/bin/pppd \
    vendor/samsung/GT-I9000/prebuilt/etc/ppp/ip-up-vpn:system/etc/ppp/ip-up-vpn
  
#
# TV-Out
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/lib/lib_tvoutengine.so:system/lib/lib_tvoutengine.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libtvout_jni.so:system/lib/libtvout_jni.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libtvoutfimc.so:system/lib/libtvoutfimc.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libtvouthdmi.so:system/lib/libtvouthdmi.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libtvoutservice.so:system/lib/libtvoutservice.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libtvout.so:system/lib/libtvout.so \
    vendor/samsung/GT-I9000/prebuilt/lib/libs3cjpeg.so:system/lib/libs3cjpeg.so \
    vendor/samsung/GT-I9000/prebuilt/bin/tvoutserver:system/bin/tvoutserver

#
# test binary blobs
#
PRODUCT_COPY_FILES += \
    vendor/samsung/GT-I9000/prebuilt/bin/immvibed:system/bin/immvibed \
    vendor/samsung/GT-I9000/prebuilt/bin/racoon:system/bin/racoon

